name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "minepawn.sbs"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "minepawn.sbs"

[env.production]
name = "cloudflare-docker-proxy"
 routes = [
   { pattern = "myd.minepawn.sbs", custom_domain = true },
   { pattern = "quay.minepawn.sbs", custom_domain = true },
   { pattern = "gcr.minepawn.sbs", custom_domain = true },
   { pattern = "k8s-gcr.minepawn.sbs", custom_domain = true },
   { pattern = "k8s.minepawn.sbs", custom_domain = true },
   { pattern = "ghcr.minepawn.sbs", custom_domain = true },
   { pattern = "cloudsmith.minepawn.sbs", custom_domain = true },
   { pattern = "mydhub.minepawn.sbs", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.minepawn.sbs", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
